server:
  port: 0 # For a random port use

camunda.bpm:
  client:
    base-url: http://localhost:8080/engine-rest # The URL pointing to the Camunda Platform Runtime REST API
    async-response-timeout: 1000 # Defines the maximum duration of the long-polling request
    worker-id: pawga777-client # Identifies the worker towards the Engine

